### ISSUE TITLE
Is there a jar file I can download?

### ISSUE THREAD

**Issue by djinnome** [sbgn/cd2sbgnml#8]
Hi folks,

I have java 1.6, and when I tried

```bash
mvn clean
```

I got the following error message:

```bash
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/codehaus/plexus/classworlds/launcher/Launcher : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

Please advise.

Jeremy

**Comment by djinnome** [comment]
Nevermind: https://github.com/sbgn/cd2sbgnml/releases

**Comment by djinnome** [comment]
Nevermind: https://github.com/sbgn/cd2sbgnml/releases

**Comment by djinnome** [comment]
OK, folks, when I downloaded  [cd2sbgnml-0.4.4-app.jar](https://github.com/sbgn/cd2sbgnml/releases/tag/0.4.4)
to `target` and ran `./sbgnml2cd.sh`


I got the following error message:
```bash
Exception in thread "main" java.lang.UnsupportedClassVersionError: fr/curie/cd2sbgnml/Sbgnml2CdScript : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

Same thing when I downloaded  `cd2sbgnml-0.4.5-app.jar` and updated `sbgnml2cd.sh` to point to the 0.4.5 version.

Please advise.

**Comment by cannin** [comment]
@djinnome does this help: https://github.com/cannin/covid19-sbgn/tree/master/scripts the jar is there and a Bash script showing a use case

**Comment by cannin** [comment]
And I'm using Java 1.8: https://github.com/cannin/covid19-sbgn/blob/master/.travis.yml

**Comment by ugurdogrusoz** [comment]
https://stackoverflow.com/a/11432195

@djinnome I think you're using an older version of JRE to run where this jar was built with a new version. Just Java 1.8 as your run time environment as well and you should be OK.

**Comment by cannin** [comment]
Closing this; re-open if the issue was not addressed satisfactorily.
